name: v2t_vmdt
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.43
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - gcc=11.4.0
  - gcc_impl_linux-64=11.4.0
  - gxx=11.4.0
  - gxx_impl_linux-64=11.4.0
  - kernel-headers_linux-64=3.10.0
  - ld_impl_linux-64=2.43
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-devel_linux-64=11.4.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libsanitizer=11.4.0
  - libsqlite=3.49.2
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=11.4.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.0
  - pip=25.1.1
  - python=3.12.10
  - readline=8.2
  - sysroot_linux-64=2.17
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - pip:
      - accelerate==1.7.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anthropic==0.51.0
      - anyio==4.9.0
      - attrs==25.3.0
      - av==14.4.0
      - boto3==1.38.21
      - botocore==1.38.21
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - cmake==4.0.2
      - datasets==3.6.0
      - decord==0.6.0
      - dill==0.3.8
      - distro==1.9.0
      - einops==0.8.1
      - filelock==3.13.1
      - flash-attn==2.7.4.post1
      - frozenlist==1.6.0
      - fsspec==2024.6.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.31.4
      - idna==3.10
      - imageio==2.37.0
      - jinja2==3.1.4
      - jiter==0.10.0
      - jmespath==1.0.1
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.4.4
      - multiprocess==0.70.16
      - networkx==3.3
      - ninja==1.11.1.4
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.81.0
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.0.0
      - propcache==0.3.1
      - psutil==7.0.0
      - pyarrow==20.0.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - qwen-vl-utils==0.0.11
      - regex==2024.11.6
      - requests==2.32.3
      - s3transfer==0.12.0
      - safetensors==0.5.3
      - setuptools==70.2.0
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.13.1
      - timm==1.0.15
      - tokenizers==0.21.1
      - torch==2.6.0+cu124
      - torchaudio==2.7.0+cu128
      - torchvision==0.21.0+cu124
      - tqdm==4.67.1
      - transformers==4.52.2
      - triton==3.2.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.4.0
      - xformers==0.0.29.post3
      - xxhash==3.5.0
      - yarl==1.20.0
